cask_args appdir: '/Applications'

# Java development
cask 'java' unless system '/usr/libexec/java_home --failfast'

cask 'intellij-idea'

brew 'maven'
brew 'maven-completion'

brew 'gradle'
brew 'groovy', args: ['--with-invokedynamic']

brew 'jmeter', args: ['--with-plugins']

# Install Spring Boot
tap 'pivotal/tap'
brew 'springboot'
#brew 'spring-completion'
#brew 'rest-shell'

# Android
#brew 'android-sdk'

# brew 'infer'
